# Generated by Django 4.2.13 on 2024-06-14 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=120)),
                ('subscriber_plan', models.CharField(choices=[('basic', 'Basic Plan'), ('premium', 'Premium Plan')], max_length=250)),
                ('subscriber_cost', models.CharField(max_length=250)),
                ('paypal_sub_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
