# Generated by Django 4.2.13 on 2024-06-07 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_edited',
            field=models.DateField(auto_now=True, verbose_name='Edited Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
