# Generated by Django 4.2.13 on 2024-06-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_article_date_edited_alter_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited Date'),
        ),
    ]
