# Generated by Django 4.2.13 on 2024-06-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_alter_article_date_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='Unique_title_user'),
        ),
    ]
